// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Week4.Console;

#nullable disable

namespace CsvReaderExample2023.Migrations
{
    [DbContext(typeof(SchoolContext))]
    partial class SchoolContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Week4.Console.Student", b =>
                {
                    b.Property<string>("StudentID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecondName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StudentID");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            StudentID = "S00472973",
                            FirstName = "Elizabeth",
                            SecondName = "Andersen"
                        },
                        new
                        {
                            StudentID = "S00806042",
                            FirstName = "Catherine",
                            SecondName = "Autier Miconi"
                        },
                        new
                        {
                            StudentID = "S00360626",
                            FirstName = "Thomas",
                            SecondName = "Axen"
                        },
                        new
                        {
                            StudentID = "S00873144",
                            FirstName = "Jean Philippe",
                            SecondName = "Bagel"
                        },
                        new
                        {
                            StudentID = "S00278258",
                            FirstName = "Anna",
                            SecondName = "Bedecs"
                        },
                        new
                        {
                            StudentID = "S00046565",
                            FirstName = "John",
                            SecondName = "Edwards"
                        },
                        new
                        {
                            StudentID = "S00698845",
                            FirstName = "Alexander",
                            SecondName = "Eggerer"
                        },
                        new
                        {
                            StudentID = "S00389325",
                            FirstName = "Michael",
                            SecondName = "Entin"
                        },
                        new
                        {
                            StudentID = "S00170776",
                            FirstName = "Daniel",
                            SecondName = "Goldschmidt"
                        },
                        new
                        {
                            StudentID = "S00274643",
                            FirstName = "Antonio",
                            SecondName = "Gratacos Solsona"
                        },
                        new
                        {
                            StudentID = "S00287450",
                            FirstName = "Carlos",
                            SecondName = "Grilo"
                        },
                        new
                        {
                            StudentID = "S00636735",
                            FirstName = "Jonas",
                            SecondName = "Hasselberg"
                        },
                        new
                        {
                            StudentID = "S00947280",
                            FirstName = "Peter",
                            SecondName = "Krschne"
                        },
                        new
                        {
                            StudentID = "S00757976",
                            FirstName = "Helena",
                            SecondName = "Kupkova"
                        },
                        new
                        {
                            StudentID = "S00540216",
                            FirstName = "Christina",
                            SecondName = "Lee"
                        },
                        new
                        {
                            StudentID = "S00387552",
                            FirstName = "Soo Jung",
                            SecondName = "Lee"
                        },
                        new
                        {
                            StudentID = "S00483498",
                            FirstName = "George",
                            SecondName = "Li"
                        },
                        new
                        {
                            StudentID = "S00380454",
                            FirstName = "Run",
                            SecondName = "Liu"
                        },
                        new
                        {
                            StudentID = "S00442638",
                            FirstName = "Andre",
                            SecondName = "Ludick"
                        },
                        new
                        {
                            StudentID = "S00360809",
                            FirstName = "Sven",
                            SecondName = "Mortensen"
                        },
                        new
                        {
                            StudentID = "S00114203",
                            FirstName = "Martin",
                            SecondName = "O�Donnell"
                        },
                        new
                        {
                            StudentID = "S00452407",
                            FirstName = "Francisco",
                            SecondName = "P�rez-Olaeta"
                        },
                        new
                        {
                            StudentID = "S00971382",
                            FirstName = "Amritansh",
                            SecondName = "Raghav"
                        },
                        new
                        {
                            StudentID = "S00156910",
                            FirstName = "Luciana",
                            SecondName = "Ramos"
                        },
                        new
                        {
                            StudentID = "S00002529",
                            FirstName = "John",
                            SecondName = "Rodman"
                        },
                        new
                        {
                            StudentID = "S00241057",
                            FirstName = "Bernard",
                            SecondName = "Tham"
                        },
                        new
                        {
                            StudentID = "S00634533",
                            FirstName = "Karen",
                            SecondName = "Toh"
                        },
                        new
                        {
                            StudentID = "S00599865",
                            FirstName = "Roland",
                            SecondName = "Wacker"
                        },
                        new
                        {
                            StudentID = "S00078018",
                            FirstName = "Ming-Yang",
                            SecondName = "Xie"
                        },
                        new
                        {
                            StudentID = "S00585868",
                            FirstName = "Elizabeth A.",
                            SecondName = "Andersen"
                        },
                        new
                        {
                            StudentID = "S00113203",
                            FirstName = "Bryn Paul",
                            SecondName = "Dunton"
                        },
                        new
                        {
                            StudentID = "S00633249",
                            FirstName = "Stuart",
                            SecondName = "Glasson"
                        },
                        new
                        {
                            StudentID = "S00880651",
                            FirstName = "Satomi",
                            SecondName = "Hayakawa"
                        },
                        new
                        {
                            StudentID = "S00586142",
                            FirstName = "Amaya",
                            SecondName = "Hernandez-Echevarria"
                        },
                        new
                        {
                            StudentID = "S00303021",
                            FirstName = "Madeleine",
                            SecondName = "Kelley"
                        },
                        new
                        {
                            StudentID = "S00932913",
                            FirstName = "Mikael",
                            SecondName = "Sandberg"
                        },
                        new
                        {
                            StudentID = "S00449490",
                            FirstName = "Naoki",
                            SecondName = "Sato"
                        },
                        new
                        {
                            StudentID = "S00913453",
                            FirstName = "Luis",
                            SecondName = "Sousa"
                        },
                        new
                        {
                            StudentID = "S00225481",
                            FirstName = "Cornelia",
                            SecondName = "Weiler"
                        },
                        new
                        {
                            StudentID = "S00838203",
                            FirstName = "Andrew",
                            SecondName = "Cencini"
                        },
                        new
                        {
                            StudentID = "S00342403",
                            FirstName = "Nancy",
                            SecondName = "Freehafer"
                        },
                        new
                        {
                            StudentID = "S00978944",
                            FirstName = "Laura",
                            SecondName = "Giussani"
                        },
                        new
                        {
                            StudentID = "S00430473",
                            FirstName = "Anne",
                            SecondName = "Hellung-Larsen"
                        },
                        new
                        {
                            StudentID = "S00023092",
                            FirstName = "Jan",
                            SecondName = "Kotas"
                        },
                        new
                        {
                            StudentID = "S00413210",
                            FirstName = "Michael",
                            SecondName = "Neipper"
                        },
                        new
                        {
                            StudentID = "S00213687",
                            FirstName = "Mariya",
                            SecondName = "Sergienko"
                        },
                        new
                        {
                            StudentID = "S00132212",
                            FirstName = "Steven",
                            SecondName = "Thorpe"
                        },
                        new
                        {
                            StudentID = "S00967156",
                            FirstName = "Robert",
                            SecondName = "Zare"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
